In [1]:
from __future__ import print_function
import torch


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 4.6837e-39, 9.2755e-39],
        [1.0837e-38, 8.4490e-39, 1.1112e-38],
        [9.2755e-39, 8.4490e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3290, 0.5798, 0.1594],
        [0.4429, 0.2799, 0.1163],
        [0.4131, 0.3411, 0.5424],
        [0.9644, 0.7934, 0.1184],
        [0.7655, 0.0608, 0.6179]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)



tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)



tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3215,  1.0586,  0.8491],
        [-0.5911, -1.1308, -0.6134],
        [-0.4560, -1.1812,  0.4756],
        [-0.4251,  1.8101, -0.0405],
        [-0.4954, -0.3765,  0.2138]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)



tensor([[ 0.7630,  1.7707,  1.6602],
        [ 0.3688, -0.7689,  0.2026],
        [-0.1492, -0.3508,  0.7739],
        [ 0.4904,  2.0880,  0.2059],
        [ 0.3485, -0.2506,  0.3597]])


In [9]:
print(torch.add(x, y))



tensor([[ 0.7630,  1.7707,  1.6602],
        [ 0.3688, -0.7689,  0.2026],
        [-0.1492, -0.3508,  0.7739],
        [ 0.4904,  2.0880,  0.2059],
        [ 0.3485, -0.2506,  0.3597]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)



tensor([[ 0.7630,  1.7707,  1.6602],
        [ 0.3688, -0.7689,  0.2026],
        [-0.1492, -0.3508,  0.7739],
        [ 0.4904,  2.0880,  0.2059],
        [ 0.3485, -0.2506,  0.3597]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.7630,  1.7707,  1.6602],
        [ 0.3688, -0.7689,  0.2026],
        [-0.1492, -0.3508,  0.7739],
        [ 0.4904,  2.0880,  0.2059],
        [ 0.3485, -0.2506,  0.3597]])


In [12]:
print(x[:, 1])

tensor([ 1.0586, -1.1308, -1.1812,  1.8101, -0.3765])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())



torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
def soma(s,y):
    return s*y

In [17]:
soma(5,2)

10

In [18]:
soma(8,9)

72